name: pos_sa_demo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0-56.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  pretty_dio_logger: ^1.3.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4
  firebase_analytics: ^10.7.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  google_directions_api: ^0.9.1
  geocoding: ^2.1.1
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700